USE THE_RED_DB;
GO
CREATE VIEW V_COMMANDES_PAR_CLIENT AS
SELECT
    C.ID_CLIENT,
    C.NOM AS NOM_CLIENT,
    CMD.ID_CMD,
    CMD.DATE_CMD,
    CMD.STATUT
FROM CLIENT C
JOIN COMMANDE CMD ON C.ID_CLIENT = CMD.ID_CLIENT;
GO

CREATE VIEW V_PRODUITS_FOURNISSEURS AS
SELECT
    P.ID_PRODUIT,
    P.NOM AS NOM_PRODUIT,
    CAT.NOM_CATEGORIE,
    F.NOM AS NOM_FOURNISSEUR
FROM PRODUIT P
JOIN CATEGORIE CAT ON P.ID_CATEGORI = CAT.ID_CATEGORI
JOIN FOURNISSEUR F ON P.ID_FOURNISS = F.ID_FOURNISS;
GO

CREATE VIEW V_DETAIL_COMMANDE AS
SELECT
    CMD.ID_CMD,
    CMD.DATE_CMD,
    C.NOM AS NOM_CLIENT,
    P.NOM AS NOM_PRODUIT,
    LC.QUANTITE,
    LC.PRIX_UNITAIRE,
    (LC.QUANTITE * LC.PRIX_UNITAIRE) AS MONTANT_LIGNE
FROM COMMANDE CMD
JOIN CLIENT C ON CMD.ID_CLIENT = C.ID_CLIENT
JOIN LIGNE_COMMANDE LC ON CMD.ID_CMD = LC.ID_CMD
JOIN PRODUIT P ON LC.ID_PRODUIT = P.ID_PRODUIT;
GO
