USE THE_RED_DB;
GO

IF OBJECT_ID('V_DETAIL_COMMANDE', 'V') IS NOT NULL DROP VIEW V_DETAIL_COMMANDE;
IF OBJECT_ID('V_PRODUITS_FOURNISSEURS', 'V') IS NOT NULL DROP VIEW V_PRODUITS_FOURNISSEURS;
IF OBJECT_ID('V_COMMANDES_PAR_CLIENT', 'V') IS NOT NULL DROP VIEW V_COMMANDES_PAR_CLIENT;
GO

DROP TABLE LIVRAISON;
DROP TABLE PAIEMENT;
DROP TABLE FACTURE;
DROP TABLE LIGNE_COMMANDE;
DROP TABLE STOCK;
DROP TABLE COMMANDE;
DROP TABLE PRODUIT;
DROP TABLE FOURNISSEUR;
DROP TABLE CATEGORIE;
DROP TABLE EMPLOYE;
DROP TABLE CLIENT;
GO

