SELECT * FROM V_COMMANDES_PAR_CLIENT;
SELECT * FROM V_PRODUITS_FOURNISSEURS;
SELECT * FROM V_DETAIL_COMMANDE;
GO
use THE_RED_DB;
GO
SELECT* FROM V_LIVRAISONS_COMPLETES;
select * from VUE_DETAIL_COMMANDE;
select * from V_COMMANDES_CLIENT;   

