USE THE_RED_DB;
GO
UPDATE COMMANDE
SET STATUT = 'LIVREE'
WHERE ID_CMD = 2;
GO

UPDATE PRODUIT
SET PRIX = PRIX * 1.05
WHERE ID_CATEGORI = 1;
GO

UPDATE STOCK
SET QTE_DISPO = QTE_DISPO - 2
WHERE ID_PRODUIT = 1;
GO

UPDATE CLIENT
SET ADRESSE = 'Longueuil'
WHERE ID_CLIENT = 2;
GO

UPDATE FOURNISSEUR
SET TELEPHONE = '+221-77-999-9999'
WHERE ID_FOURNISS = 1;
GO

DELETE FROM LIGNE_COMMANDE
WHERE ID_CMD = 4;
GO

DELETE FROM COMMANDE
WHERE ID_CMD = 4;
GO

UPDATE LIVRAISON
SET STATUT = 'LIVREE',
    DATE_RECEP = '2024-11-04'
WHERE ID_LIVRAISN = 2;
GO

UPDATE EMPLOYE
SET ROLE = 'GESTIONNAIRE'
WHERE ID_EMPLOYE = 4;
GO

DELETE FROM PAIEMENT
WHERE ID_PAIEMEN = 5;
GO
UPDATE STOCK
SET QTE_DISPO = QTE_DISPO + 10
WHERE ID_PRODUIT = 1;