CREATE DATABASE THE_RED_DB;
GO


use THE_RED_DB
CREATE TABLE CLIENT (
    ID_CLIENT      INT           NOT NULL,
    NOM            VARCHAR(100)  NOT NULL,
    TEL            VARCHAR(20)   NOT NULL,
    COURRIEL       VARCHAR(150)  NOT NULL,
    ADRESSE        VARCHAR(255)  NOT NULL,
    CONSTRAINT PK_CLIENT PRIMARY KEY (ID_CLIENT),
    CONSTRAINT UQ_CLIENT_TEL UNIQUE (TEL),
    CONSTRAINT UQ_CLIENT_COURRIEL UNIQUE (COURRIEL)
);
GO

CREATE TABLE EMPLOYE (
    ID_EMPLOYE INT           NOT NULL,
    NOM        VARCHAR(100)  NOT NULL,
    ROLE       VARCHAR(50)   NOT NULL,
    LOGIN      VARCHAR(50)   NOT NULL,
    MOT_PASSE  VARCHAR(255)  NOT NULL,
    CONSTRAINT PK_EMPLOYE PRIMARY KEY (ID_EMPLOYE),
    CONSTRAINT UQ_EMPLOYE_LOGIN UNIQUE (LOGIN)
);
GO

CREATE TABLE CATEGORIE (
    ID_CATEGORI    INT           NOT NULL,
    NOM_CATEGORIE  VARCHAR(100)  NOT NULL,
    CONSTRAINT PK_CATEGORIE PRIMARY KEY (ID_CATEGORI)
);
GO

CREATE TABLE FOURNISSEUR (
    ID_FOURNISS INT           NOT NULL,
    NOM         VARCHAR(150)  NOT NULL,
    TELEPHONE   VARCHAR(20)   NULL,
    MAIL        VARCHAR(150)  NULL,
    ADRESSE     VARCHAR(255)  NULL,
    CONSTRAINT PK_FOURNISSEUR PRIMARY KEY (ID_FOURNISS)
);
GO

CREATE TABLE PRODUIT (
    ID_PRODUI    INT           NOT NULL,
    NOM          VARCHAR(150)  NOT NULL,
    DESCRIPTION  VARCHAR(255)  NULL,
    PRIX         DECIMAL(10,2) NOT NULL,
    ID_CATEGORI  INT           NOT NULL,
    ID_FOURNISS  INT           NOT NULL,
    CONSTRAINT PK_PRODUIT PRIMARY KEY (ID_PRODUI),
    CONSTRAINT FK_PRODUIT_CATEGORIE
        FOREIGN KEY (ID_CATEGORI) REFERENCES CATEGORIE(ID_CATEGORI),
    CONSTRAINT FK_PRODUIT_FOURNISSEUR
        FOREIGN KEY (ID_FOURNISS) REFERENCES FOURNISSEUR(ID_FOURNISS),
    CONSTRAINT CHK_PRODUIT_PRIX_POSITIF
        CHECK (PRIX >= 0)
);
GO

CREATE TABLE COMMANDE (
    ID_CMD     INT           NOT NULL,
    DATE_CMD   DATE          NOT NULL
        CONSTRAINT DF_COMMANDE_DATE_CMD DEFAULT (GETDATE()),
    STATUT     VARCHAR(20)   NOT NULL
        CONSTRAINT DF_COMMANDE_STATUT DEFAULT ('EN COURS'),
    ID_CLIENT  INT           NOT NULL,
    ID_EMPLY   INT           NOT NULL,
    CONSTRAINT PK_COMMANDE PRIMARY KEY (ID_CMD),
    CONSTRAINT FK_COMMANDE_CLIENT
        FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    CONSTRAINT FK_COMMANDE_EMPLOYE
        FOREIGN KEY (ID_EMPLY) REFERENCES EMPLOYE(ID_EMPLOYE),
    CONSTRAINT CHK_COMMANDE_STATUT
        CHECK (STATUT IN ('EN COURS','LIVREE','ANNULEE'))
);
GO

CREATE TABLE LIGNE_COMMANDE (
    ID_CMD        INT           NOT NULL,
    ID_PRODUI    INT           NOT NULL,
    QUANTITE      INT           NOT NULL,
    PRIX_UNITAIRE DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_LIGNE_COMMANDE PRIMARY KEY (ID_CMD, ID_PRODUI),
    CONSTRAINT FK_LIGNE_COMMANDE_COMMANDE
        FOREIGN KEY (ID_CMD) REFERENCES COMMANDE(ID_CMD),
    CONSTRAINT FK_LIGNE_COMMANDE_PRODUIT
        FOREIGN KEY (ID_PRODUI) REFERENCES PRODUIT(ID_PRODUIT),
    CONSTRAINT CHK_LIGNE_COMMANDE_QTE_POSITIVE
        CHECK (QUANTITE > 0),
    CONSTRAINT CHK_LIGNE_COMMANDE_PRIX_POSITIF
        CHECK (PRIX_UNITAIRE >= 0)
);
GO

CREATE TABLE STOCK (
    ID_STOCK   INT  NOT NULL,
    ID_PRODUIT INT  NOT NULL,
    QTE_DISPO  INT  NOT NULL,
    DATE_MAJ   DATE NOT NULL
        CONSTRAINT DF_STOCK_DATE_MAJ DEFAULT (GETDATE()),
    CONSTRAINT PK_STOCK PRIMARY KEY (ID_STOCK),
    CONSTRAINT FK_STOCK_PRODUIT
        FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT),
    CONSTRAINT CHK_STOCK_QTE_NON_NEG
        CHECK (QTE_DISPO >= 0)
);
GO

CREATE TABLE FACTURE (
    ID_FACTURE INT           NOT NULL,
    DATE       DATE          NOT NULL,
    MONTANT    DECIMAL(10,2) NOT NULL,
    ID_CMD     INT           NOT NULL,
    CONSTRAINT PK_FACTURE PRIMARY KEY (ID_FACTURE),
    CONSTRAINT FK_FACTURE_COMMANDE
        FOREIGN KEY (ID_CMD) REFERENCES COMMANDE(ID_CMD),
    CONSTRAINT CHK_FACTURE_MONTANT_POSITIF
        CHECK (MONTANT >= 0)
);
GO

CREATE TABLE PAIEMENT (
    ID_PAIEMEN  INT           NOT NULL,
    DATE_PAIMT  DATE          NOT NULL,
    MONTANT     DECIMAL(10,2) NOT NULL,
    MODE_PAIM   VARCHAR(50)   NOT NULL,
    ID_CMD      INT           NOT NULL,
    CONSTRAINT PK_PAIEMENT PRIMARY KEY (ID_PAIEMEN),
    CONSTRAINT FK_PAIEMENT_COMMANDE
        FOREIGN KEY (ID_CMD) REFERENCES COMMANDE(ID_CMD),
    CONSTRAINT CHK_PAIEMENT_MONTANT_POSITIF
        CHECK (MONTANT >= 0)
);
GO

CREATE TABLE LIVRAISON (
    ID_LIVRAISN INT           NOT NULL,
    DATE_ENVOI  DATE          NOT NULL,
    DATE_RECEP  DATE          NULL,
    STATUT      VARCHAR(20)   NOT NULL,
    ID_CMD      INT           NOT NULL,
    ID_FOURNISS INT           NOT NULL,
    ID_EMPLOYE  INT           NOT NULL,
    CONSTRAINT PK_LIVRAISON PRIMARY KEY (ID_LIVRAISN),
    CONSTRAINT FK_LIVRAISON_COMMANDE
        FOREIGN KEY (ID_CMD) REFERENCES COMMANDE(ID_CMD),
    CONSTRAINT FK_LIVRAISON_FOURNISSEUR
        FOREIGN KEY (ID_FOURNISS) REFERENCES FOURNISSEUR(ID_FOURNISS),
    CONSTRAINT FK_LIVRAISON_EMPLOYE
        FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYE(ID_EMPLOYE),
    CONSTRAINT CHK_LIVRAISON_STATUT
        CHECK (STATUT IN ('EN PREPARATION','EN TRANSIT','LIVREE','RETARDEE'))
);
use THE_RED_DB
GO
CREATE TABLE FOURNITURE_PRODUIT (
    ID_PRODUIT   INT NOT NULL,
    ID_FOURNISS  INT NOT NULL,
    PRIX_FOURNISSEUR DECIMAL(10,2) NULL,
    DELAI_LIVRAISON  INT NULL,
    REFERENCE_FOURNISSEUR VARCHAR(100) NULL,

    CONSTRAINT PK_FOURNITURE_PRODUIT PRIMARY KEY (ID_PRODUIT, ID_FOURNISS),

    CONSTRAINT FK_FOURNITURE_PRODUIT_PRODUIT
        FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT),

    CONSTRAINT FK_FOURNITURE_PRODUIT_FOURNISSEUR
        FOREIGN KEY (ID_FOURNISS) REFERENCES FOURNISSEUR(ID_FOURNISS)
);
GO

CREATE TABLE MAJ_STOCK (
    ID_STOCK    INT NOT NULL,
    ID_EMPLOYE  INT NOT NULL,
    DATE_MAJ    DATE NOT NULL CONSTRAINT DF_MAJ_STOCK_DATE DEFAULT (GETDATE()),
    QUANTITE_MODIFIEE INT NULL,
    TYPE_ACTION VARCHAR(50) NOT NULL,

    CONSTRAINT PK_MAJ_STOCK PRIMARY KEY (ID_STOCK, ID_EMPLOYE),

    CONSTRAINT FK_MAJ_STOCK_STOCK
        FOREIGN KEY (ID_STOCK) REFERENCES STOCK(ID_STOCK),

    CONSTRAINT FK_MAJ_STOCK_EMPLOYE
        FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYE(ID_EMPLOYE)
);
GO

-- End of SQLQuery1.sql