ALTER TABLE LIGNE_COMMANDE
ADD REMISE DECIMAL(5,2) CONSTRAINT DF_LIGNE_COMMANDE_REMISE DEFAULT (0);
GO

ALTER TABLE FACTURE
ADD NUMERO_FACTURE_EXTERNE VARCHAR(50) NULL;
GO

ALTER TABLE CLIENT
ALTER COLUMN NOM VARCHAR(150) NOT NULL;
GO

ALTER TABLE CLIENT
ADD VILLE VARCHAR(100) NULL;
GO

ALTER TABLE FOURNISSEUR
ADD PAYS VARCHAR(100) NULL;
GO

ALTER TABLE PAIEMENT
ADD CONSTRAINT CHK_PAIEMENT_MODE
CHECK (MODE_PAIM IN ('CARTE','ESPECES','VIREMENT','PAYPAL'));
GO

ALTER TABLE EMPLOYE
ADD EMAIL_PROFESSIONNEL VARCHAR(150) NULL;
GO

ALTER TABLE EMPLOYE
ADD CONSTRAINT CHK_EMPLOYE_ROLE
CHECK (ROLE IN ('VENDEUR','GESTIONNAIRE','COMPTABLE','LOGISTICIEN'));
GO

ALTER TABLE PRODUIT
ADD NOTE VARCHAR(255) NULL;
GO

ALTER TABLE LIVRAISON
ADD CONSTRAINT CHK_LIVRAISON_DATES
CHECK (DATE_RECEP IS NULL OR DATE_RECEP >= DATE_ENVOI);
GO
