USE THE_RED_DB;
GO
CREATE INDEX IX_COMMANDE_ID_CLIENT
    ON COMMANDE(ID_CLIENT);

CREATE INDEX IX_COMMANDE_ID_EMPLY
    ON COMMANDE(ID_EMPLY);

CREATE INDEX IX_LIGNE_COMMANDE_ID_PRODUIT
    ON LIGNE_COMMANDE(ID_PRODUIT);

CREATE INDEX IX_PRODUIT_ID_CATEGORI
    ON PRODUIT(ID_CATEGORI);

CREATE INDEX IX_PRODUIT_ID_FOURNISS
    ON PRODUIT(ID_FOURNISS);

CREATE INDEX IX_STOCK_ID_PRODUIT
    ON STOCK(ID_PRODUIT);

CREATE INDEX IX_FACTURE_ID_CMD
    ON FACTURE(ID_CMD);

CREATE INDEX IX_PAIEMENT_ID_CMD
    ON PAIEMENT(ID_CMD);

CREATE INDEX IX_LIVRAISON_ID_CMD
    ON LIVRAISON(ID_CMD);

CREATE INDEX IX_LIVRAISON_ID_FOURNISS
    ON LIVRAISON(ID_FOURNISS);
GO
